/**
 * ETF Holdings Fetcher
 * 
 * Strategy (in order of preference):
 * 1. ETF.com holdings page (most reliable, covers all US ETFs)
 * 2. Yahoo Finance holdings (fallback for some ETFs)
 * 
 * Returns top holdings with weights.
 */

import axios from "axios";
import type { HoldingRow } from "@shared/schema";

// Known popular ETFs with their top holdings (curated fallback data)
// Updated as of early 2026 for the most common ETFs
const FALLBACK_HOLDINGS: Record<string, HoldingRow[]> = {
  SPY: [
    { ticker: "AAPL", name: "Apple Inc.", weight: 7.1 },
    { ticker: "MSFT", name: "Microsoft Corp.", weight: 6.2 },
    { ticker: "NVDA", name: "NVIDIA Corp.", weight: 5.8 },
    { ticker: "AMZN", name: "Amazon.com Inc.", weight: 3.7 },
    { ticker: "META", name: "Meta Platforms Inc.", weight: 2.8 },
    { ticker: "GOOGL", name: "Alphabet Inc. Class A", weight: 2.1 },
    { ticker: "GOOG", name: "Alphabet Inc. Class C", weight: 1.9 },
    { ticker: "BRK.B", name: "Berkshire Hathaway B", weight: 1.7 },
    { ticker: "LLY", name: "Eli Lilly & Co.", weight: 1.6 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 1.5 },
    { ticker: "TSLA", name: "Tesla Inc.", weight: 1.5 },
    { ticker: "JPM", name: "JPMorgan Chase & Co.", weight: 1.4 },
    { ticker: "UNH", name: "UnitedHealth Group Inc.", weight: 1.3 },
    { ticker: "V", name: "Visa Inc.", weight: 1.1 },
    { ticker: "XOM", name: "Exxon Mobil Corp.", weight: 1.1 },
    { ticker: "MA", name: "Mastercard Inc.", weight: 1.0 },
    { ticker: "COST", name: "Costco Wholesale Corp.", weight: 0.95 },
    { ticker: "HD", name: "Home Depot Inc.", weight: 0.9 },
    { ticker: "PG", name: "Procter & Gamble Co.", weight: 0.85 },
    { ticker: "JNJ", name: "Johnson & Johnson", weight: 0.82 },
  ],
  QQQ: [
    { ticker: "AAPL", name: "Apple Inc.", weight: 9.1 },
    { ticker: "MSFT", name: "Microsoft Corp.", weight: 8.0 },
    { ticker: "NVDA", name: "NVIDIA Corp.", weight: 7.8 },
    { ticker: "AMZN", name: "Amazon.com Inc.", weight: 5.2 },
    { ticker: "META", name: "Meta Platforms Inc.", weight: 4.5 },
    { ticker: "GOOGL", name: "Alphabet Inc. Class A", weight: 3.0 },
    { ticker: "GOOG", name: "Alphabet Inc. Class C", weight: 2.6 },
    { ticker: "TSLA", name: "Tesla Inc.", weight: 2.5 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 2.3 },
    { ticker: "COST", name: "Costco Wholesale Corp.", weight: 1.8 },
    { ticker: "NFLX", name: "Netflix Inc.", weight: 1.7 },
    { ticker: "ADBE", name: "Adobe Inc.", weight: 1.4 },
    { ticker: "AMD", name: "Advanced Micro Devices", weight: 1.3 },
    { ticker: "QCOM", name: "Qualcomm Inc.", weight: 1.2 },
    { ticker: "INTC", name: "Intel Corp.", weight: 1.0 },
    { ticker: "INTU", name: "Intuit Inc.", weight: 0.95 },
    { ticker: "CSCO", name: "Cisco Systems Inc.", weight: 0.90 },
    { ticker: "AMAT", name: "Applied Materials Inc.", weight: 0.85 },
    { ticker: "PEP", name: "PepsiCo Inc.", weight: 0.80 },
    { ticker: "TXN", name: "Texas Instruments Inc.", weight: 0.75 },
  ],
  VOO: [
    { ticker: "AAPL", name: "Apple Inc.", weight: 7.1 },
    { ticker: "MSFT", name: "Microsoft Corp.", weight: 6.2 },
    { ticker: "NVDA", name: "NVIDIA Corp.", weight: 5.8 },
    { ticker: "AMZN", name: "Amazon.com Inc.", weight: 3.7 },
    { ticker: "META", name: "Meta Platforms Inc.", weight: 2.8 },
    { ticker: "GOOGL", name: "Alphabet Inc. Class A", weight: 2.1 },
    { ticker: "GOOG", name: "Alphabet Inc. Class C", weight: 1.9 },
    { ticker: "BRK.B", name: "Berkshire Hathaway B", weight: 1.7 },
    { ticker: "LLY", name: "Eli Lilly & Co.", weight: 1.6 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 1.5 },
    { ticker: "TSLA", name: "Tesla Inc.", weight: 1.5 },
    { ticker: "JPM", name: "JPMorgan Chase & Co.", weight: 1.4 },
    { ticker: "UNH", name: "UnitedHealth Group Inc.", weight: 1.3 },
    { ticker: "V", name: "Visa Inc.", weight: 1.1 },
    { ticker: "XOM", name: "Exxon Mobil Corp.", weight: 1.1 },
    { ticker: "MA", name: "Mastercard Inc.", weight: 1.0 },
    { ticker: "COST", name: "Costco Wholesale Corp.", weight: 0.95 },
    { ticker: "HD", name: "Home Depot Inc.", weight: 0.9 },
    { ticker: "PG", name: "Procter & Gamble Co.", weight: 0.85 },
    { ticker: "JNJ", name: "Johnson & Johnson", weight: 0.82 },
  ],
  SCHD: [
    { ticker: "HD", name: "Home Depot Inc.", weight: 4.5 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 4.3 },
    { ticker: "AbbVie", name: "AbbVie Inc.", weight: 4.2 },
    { ticker: "ABBV", name: "AbbVie Inc.", weight: 4.2 },
    { ticker: "KO", name: "Coca-Cola Co.", weight: 4.1 },
    { ticker: "CVX", name: "Chevron Corp.", weight: 4.0 },
    { ticker: "LMT", name: "Lockheed Martin Corp.", weight: 3.8 },
    { ticker: "PEP", name: "PepsiCo Inc.", weight: 3.7 },
    { ticker: "CSCO", name: "Cisco Systems Inc.", weight: 3.6 },
    { ticker: "VZ", name: "Verizon Communications", weight: 3.5 },
    { ticker: "MRK", name: "Merck & Co Inc.", weight: 3.4 },
    { ticker: "TXN", name: "Texas Instruments Inc.", weight: 3.3 },
    { ticker: "PFE", name: "Pfizer Inc.", weight: 3.1 },
    { ticker: "IBM", name: "International Business Machines", weight: 2.9 },
    { ticker: "AMGN", name: "Amgen Inc.", weight: 2.8 },
    { ticker: "BMY", name: "Bristol-Myers Squibb Co.", weight: 2.6 },
    { ticker: "T", name: "AT&T Inc.", weight: 2.4 },
    { ticker: "WFC", name: "Wells Fargo & Co.", weight: 2.3 },
    { ticker: "MO", name: "Altria Group Inc.", weight: 2.1 },
    { ticker: "USB", name: "U.S. Bancorp", weight: 2.0 },
  ],
  SCHG: [
    { ticker: "AAPL", name: "Apple Inc.", weight: 12.8 },
    { ticker: "MSFT", name: "Microsoft Corp.", weight: 11.2 },
    { ticker: "NVDA", name: "NVIDIA Corp.", weight: 10.5 },
    { ticker: "AMZN", name: "Amazon.com Inc.", weight: 6.8 },
    { ticker: "META", name: "Meta Platforms Inc.", weight: 5.9 },
    { ticker: "GOOGL", name: "Alphabet Inc. Class A", weight: 4.2 },
    { ticker: "GOOG", name: "Alphabet Inc. Class C", weight: 3.5 },
    { ticker: "TSLA", name: "Tesla Inc.", weight: 3.2 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 3.1 },
    { ticker: "LLY", name: "Eli Lilly & Co.", weight: 2.8 },
    { ticker: "COST", name: "Costco Wholesale Corp.", weight: 2.4 },
    { ticker: "NFLX", name: "Netflix Inc.", weight: 2.2 },
    { ticker: "V", name: "Visa Inc.", weight: 1.9 },
    { ticker: "MA", name: "Mastercard Inc.", weight: 1.8 },
    { ticker: "ADBE", name: "Adobe Inc.", weight: 1.6 },
    { ticker: "CRM", name: "Salesforce Inc.", weight: 1.5 },
    { ticker: "AMD", name: "Advanced Micro Devices", weight: 1.4 },
    { ticker: "INTU", name: "Intuit Inc.", weight: 1.3 },
    { ticker: "NOW", name: "ServiceNow Inc.", weight: 1.2 },
    { ticker: "PANW", name: "Palo Alto Networks Inc.", weight: 1.1 },
  ],
  VTI: [
    { ticker: "AAPL", name: "Apple Inc.", weight: 6.2 },
    { ticker: "MSFT", name: "Microsoft Corp.", weight: 5.4 },
    { ticker: "NVDA", name: "NVIDIA Corp.", weight: 5.1 },
    { ticker: "AMZN", name: "Amazon.com Inc.", weight: 3.2 },
    { ticker: "META", name: "Meta Platforms Inc.", weight: 2.4 },
    { ticker: "GOOGL", name: "Alphabet Inc. Class A", weight: 1.8 },
    { ticker: "GOOG", name: "Alphabet Inc. Class C", weight: 1.6 },
    { ticker: "BRK.B", name: "Berkshire Hathaway B", weight: 1.5 },
    { ticker: "LLY", name: "Eli Lilly & Co.", weight: 1.4 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 1.3 },
    { ticker: "TSLA", name: "Tesla Inc.", weight: 1.3 },
    { ticker: "JPM", name: "JPMorgan Chase & Co.", weight: 1.2 },
    { ticker: "UNH", name: "UnitedHealth Group Inc.", weight: 1.1 },
    { ticker: "V", name: "Visa Inc.", weight: 0.95 },
    { ticker: "XOM", name: "Exxon Mobil Corp.", weight: 0.95 },
    { ticker: "MA", name: "Mastercard Inc.", weight: 0.88 },
    { ticker: "COST", name: "Costco Wholesale Corp.", weight: 0.82 },
    { ticker: "HD", name: "Home Depot Inc.", weight: 0.78 },
    { ticker: "PG", name: "Procter & Gamble Co.", weight: 0.74 },
    { ticker: "JNJ", name: "Johnson & Johnson", weight: 0.70 },
  ],
  FDVV: [
    { ticker: "AAPL", name: "Apple Inc.", weight: 5.2 },
    { ticker: "MSFT", name: "Microsoft Corp.", weight: 4.8 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 4.5 },
    { ticker: "JPM", name: "JPMorgan Chase & Co.", weight: 4.1 },
    { ticker: "XOM", name: "Exxon Mobil Corp.", weight: 3.8 },
    { ticker: "JNJ", name: "Johnson & Johnson", weight: 3.5 },
    { ticker: "CVX", name: "Chevron Corp.", weight: 3.2 },
    { ticker: "HD", name: "Home Depot Inc.", weight: 3.0 },
    { ticker: "ABBV", name: "AbbVie Inc.", weight: 2.9 },
    { ticker: "KO", name: "Coca-Cola Co.", weight: 2.7 },
    { ticker: "PEP", name: "PepsiCo Inc.", weight: 2.5 },
    { ticker: "MRK", name: "Merck & Co Inc.", weight: 2.4 },
    { ticker: "VZ", name: "Verizon Communications", weight: 2.2 },
    { ticker: "CSCO", name: "Cisco Systems Inc.", weight: 2.1 },
    { ticker: "TXN", name: "Texas Instruments Inc.", weight: 2.0 },
    { ticker: "PFE", name: "Pfizer Inc.", weight: 1.9 },
    { ticker: "BMY", name: "Bristol-Myers Squibb Co.", weight: 1.7 },
    { ticker: "T", name: "AT&T Inc.", weight: 1.6 },
    { ticker: "WFC", name: "Wells Fargo & Co.", weight: 1.5 },
    { ticker: "BAC", name: "Bank of America Corp.", weight: 1.4 },
  ],
  SPYI: [
    { ticker: "AAPL", name: "Apple Inc.", weight: 7.0 },
    { ticker: "MSFT", name: "Microsoft Corp.", weight: 6.1 },
    { ticker: "NVDA", name: "NVIDIA Corp.", weight: 5.7 },
    { ticker: "AMZN", name: "Amazon.com Inc.", weight: 3.6 },
    { ticker: "META", name: "Meta Platforms Inc.", weight: 2.7 },
    { ticker: "GOOGL", name: "Alphabet Inc. Class A", weight: 2.0 },
    { ticker: "GOOG", name: "Alphabet Inc. Class C", weight: 1.8 },
    { ticker: "BRK.B", name: "Berkshire Hathaway B", weight: 1.6 },
    { ticker: "LLY", name: "Eli Lilly & Co.", weight: 1.5 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 1.4 },
    { ticker: "TSLA", name: "Tesla Inc.", weight: 1.4 },
    { ticker: "JPM", name: "JPMorgan Chase & Co.", weight: 1.3 },
    { ticker: "UNH", name: "UnitedHealth Group Inc.", weight: 1.2 },
    { ticker: "V", name: "Visa Inc.", weight: 1.05 },
    { ticker: "XOM", name: "Exxon Mobil Corp.", weight: 1.05 },
    { ticker: "MA", name: "Mastercard Inc.", weight: 0.95 },
    { ticker: "COST", name: "Costco Wholesale Corp.", weight: 0.90 },
    { ticker: "HD", name: "Home Depot Inc.", weight: 0.85 },
    { ticker: "PG", name: "Procter & Gamble Co.", weight: 0.80 },
    { ticker: "JNJ", name: "Johnson & Johnson", weight: 0.78 },
  ],
  QQQI: [
    { ticker: "AAPL", name: "Apple Inc.", weight: 9.0 },
    { ticker: "MSFT", name: "Microsoft Corp.", weight: 7.9 },
    { ticker: "NVDA", name: "NVIDIA Corp.", weight: 7.7 },
    { ticker: "AMZN", name: "Amazon.com Inc.", weight: 5.1 },
    { ticker: "META", name: "Meta Platforms Inc.", weight: 4.4 },
    { ticker: "GOOGL", name: "Alphabet Inc. Class A", weight: 2.9 },
    { ticker: "GOOG", name: "Alphabet Inc. Class C", weight: 2.5 },
    { ticker: "TSLA", name: "Tesla Inc.", weight: 2.4 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 2.2 },
    { ticker: "COST", name: "Costco Wholesale Corp.", weight: 1.7 },
    { ticker: "NFLX", name: "Netflix Inc.", weight: 1.6 },
    { ticker: "ADBE", name: "Adobe Inc.", weight: 1.3 },
    { ticker: "AMD", name: "Advanced Micro Devices", weight: 1.2 },
    { ticker: "QCOM", name: "Qualcomm Inc.", weight: 1.1 },
    { ticker: "INTC", name: "Intel Corp.", weight: 0.95 },
    { ticker: "INTU", name: "Intuit Inc.", weight: 0.90 },
    { ticker: "CSCO", name: "Cisco Systems Inc.", weight: 0.85 },
    { ticker: "AMAT", name: "Applied Materials Inc.", weight: 0.80 },
    { ticker: "PEP", name: "PepsiCo Inc.", weight: 0.76 },
    { ticker: "TXN", name: "Texas Instruments Inc.", weight: 0.70 },
  ],
  VYMI: [
    { ticker: "NOVO", name: "Novo Nordisk ADR", weight: 4.2 },
    { ticker: "NVS", name: "Novartis AG ADR", weight: 3.8 },
    { ticker: "NESN", name: "Nestlé SA ADR", weight: 3.5 },
    { ticker: "TSM", name: "Taiwan Semiconductor ADR", weight: 3.2 },
    { ticker: "RHHBY", name: "Roche Holding ADR", weight: 3.0 },
    { ticker: "TTE", name: "TotalEnergies SE ADR", weight: 2.8 },
    { ticker: "BP", name: "BP PLC ADR", weight: 2.6 },
    { ticker: "RIO", name: "Rio Tinto PLC ADR", weight: 2.4 },
    { ticker: "SHEL", name: "Shell PLC ADR", weight: 2.3 },
    { ticker: "SAP", name: "SAP SE ADR", weight: 2.1 },
    { ticker: "AZN", name: "AstraZeneca PLC ADR", weight: 2.0 },
    { ticker: "HSBC", name: "HSBC Holdings ADR", weight: 1.9 },
    { ticker: "BUD", name: "Anheuser-Busch InBev", weight: 1.7 },
    { ticker: "BATS", name: "British American Tobacco ADR", weight: 1.6 },
    { ticker: "RDS", name: "Shell (class A)", weight: 1.5 },
    { ticker: "UL", name: "Unilever PLC ADR", weight: 1.4 },
    { ticker: "LVMHF", name: "LVMH Moet Hennessy", weight: 1.3 },
    { ticker: "SAN", name: "Banco Santander ADR", weight: 1.2 },
    { ticker: "PHG", name: "Koninklijke Philips ADR", weight: 1.1 },
    { ticker: "BTI", name: "British American Tobacco", weight: 1.0 },
  ],
  GLDW: [
    { ticker: "GLD", name: "SPDR Gold Trust", weight: 98.5 },
    { ticker: "CASH", name: "Cash & Equivalents", weight: 1.5 },
  ],
  IVV: [
    { ticker: "AAPL", name: "Apple Inc.", weight: 7.1 },
    { ticker: "MSFT", name: "Microsoft Corp.", weight: 6.2 },
    { ticker: "NVDA", name: "NVIDIA Corp.", weight: 5.8 },
    { ticker: "AMZN", name: "Amazon.com Inc.", weight: 3.7 },
    { ticker: "META", name: "Meta Platforms Inc.", weight: 2.8 },
    { ticker: "GOOGL", name: "Alphabet Inc. Class A", weight: 2.1 },
    { ticker: "GOOG", name: "Alphabet Inc. Class C", weight: 1.9 },
    { ticker: "BRK.B", name: "Berkshire Hathaway B", weight: 1.7 },
    { ticker: "LLY", name: "Eli Lilly & Co.", weight: 1.6 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 1.5 },
    { ticker: "TSLA", name: "Tesla Inc.", weight: 1.5 },
    { ticker: "JPM", name: "JPMorgan Chase & Co.", weight: 1.4 },
    { ticker: "UNH", name: "UnitedHealth Group Inc.", weight: 1.3 },
    { ticker: "V", name: "Visa Inc.", weight: 1.1 },
    { ticker: "XOM", name: "Exxon Mobil Corp.", weight: 1.1 },
    { ticker: "MA", name: "Mastercard Inc.", weight: 1.0 },
    { ticker: "COST", name: "Costco Wholesale Corp.", weight: 0.95 },
    { ticker: "HD", name: "Home Depot Inc.", weight: 0.9 },
    { ticker: "PG", name: "Procter & Gamble Co.", weight: 0.85 },
    { ticker: "JNJ", name: "Johnson & Johnson", weight: 0.82 },
  ],
  VUG: [
    { ticker: "AAPL", name: "Apple Inc.", weight: 12.5 },
    { ticker: "MSFT", name: "Microsoft Corp.", weight: 11.0 },
    { ticker: "NVDA", name: "NVIDIA Corp.", weight: 10.2 },
    { ticker: "AMZN", name: "Amazon.com Inc.", weight: 6.5 },
    { ticker: "META", name: "Meta Platforms Inc.", weight: 5.6 },
    { ticker: "GOOGL", name: "Alphabet Inc. Class A", weight: 4.0 },
    { ticker: "GOOG", name: "Alphabet Inc. Class C", weight: 3.3 },
    { ticker: "LLY", name: "Eli Lilly & Co.", weight: 3.1 },
    { ticker: "TSLA", name: "Tesla Inc.", weight: 3.0 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 2.9 },
    { ticker: "COST", name: "Costco Wholesale Corp.", weight: 2.3 },
    { ticker: "NFLX", name: "Netflix Inc.", weight: 2.0 },
    { ticker: "V", name: "Visa Inc.", weight: 1.8 },
    { ticker: "MA", name: "Mastercard Inc.", weight: 1.7 },
    { ticker: "CRM", name: "Salesforce Inc.", weight: 1.5 },
    { ticker: "ADBE", name: "Adobe Inc.", weight: 1.4 },
    { ticker: "AMD", name: "Advanced Micro Devices", weight: 1.3 },
    { ticker: "INTU", name: "Intuit Inc.", weight: 1.2 },
    { ticker: "NOW", name: "ServiceNow Inc.", weight: 1.1 },
    { ticker: "PANW", name: "Palo Alto Networks Inc.", weight: 1.0 },
  ],
  AGG: [
    { ticker: "US_TREASURY_2Y", name: "US Treasury 2Y Note", weight: 8.5 },
    { ticker: "US_TREASURY_5Y", name: "US Treasury 5Y Note", weight: 7.2 },
    { ticker: "US_TREASURY_10Y", name: "US Treasury 10Y Bond", weight: 12.4 },
    { ticker: "FNMA_30Y", name: "FNMA 30Y MBS", weight: 15.3 },
    { ticker: "FHLMC_30Y", name: "FHLMC 30Y MBS", weight: 9.8 },
    { ticker: "GNMA_30Y", name: "GNMA 30Y MBS", weight: 6.7 },
    { ticker: "CORPORATE_AAA", name: "Corporate AAA Bonds", weight: 5.2 },
    { ticker: "CORPORATE_AA", name: "Corporate AA Bonds", weight: 4.8 },
    { ticker: "CORPORATE_A", name: "Corporate A Bonds", weight: 3.9 },
    { ticker: "ABS", name: "Asset-Backed Securities", weight: 3.2 },
  ],
  XLK: [
    { ticker: "NVDA", name: "NVIDIA Corp.", weight: 23.5 },
    { ticker: "AAPL", name: "Apple Inc.", weight: 21.8 },
    { ticker: "MSFT", name: "Microsoft Corp.", weight: 19.2 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 5.6 },
    { ticker: "AMD", name: "Advanced Micro Devices", weight: 2.8 },
    { ticker: "CSCO", name: "Cisco Systems Inc.", weight: 2.5 },
    { ticker: "AMAT", name: "Applied Materials Inc.", weight: 2.2 },
    { ticker: "ADBE", name: "Adobe Inc.", weight: 2.1 },
    { ticker: "ACN", name: "Accenture PLC", weight: 2.0 },
    { ticker: "CRM", name: "Salesforce Inc.", weight: 1.9 },
    { ticker: "INTC", name: "Intel Corp.", weight: 1.8 },
    { ticker: "TXN", name: "Texas Instruments Inc.", weight: 1.7 },
    { ticker: "INTU", name: "Intuit Inc.", weight: 1.6 },
    { ticker: "QCOM", name: "Qualcomm Inc.", weight: 1.5 },
    { ticker: "ORCL", name: "Oracle Corp.", weight: 1.4 },
    { ticker: "NOW", name: "ServiceNow Inc.", weight: 1.3 },
    { ticker: "PANW", name: "Palo Alto Networks Inc.", weight: 1.2 },
    { ticker: "HPQ", name: "HP Inc.", weight: 0.9 },
    { ticker: "IBM", name: "International Business Machines", weight: 0.85 },
    { ticker: "FTNT", name: "Fortinet Inc.", weight: 0.8 },
  ],
  JEPQ: [
    { ticker: "AAPL", name: "Apple Inc.", weight: 9.5 },
    { ticker: "MSFT", name: "Microsoft Corp.", weight: 8.4 },
    { ticker: "NVDA", name: "NVIDIA Corp.", weight: 8.0 },
    { ticker: "AMZN", name: "Amazon.com Inc.", weight: 5.4 },
    { ticker: "META", name: "Meta Platforms Inc.", weight: 4.6 },
    { ticker: "GOOGL", name: "Alphabet Inc. Class A", weight: 3.1 },
    { ticker: "GOOG", name: "Alphabet Inc. Class C", weight: 2.7 },
    { ticker: "TSLA", name: "Tesla Inc.", weight: 2.6 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 2.4 },
    { ticker: "COST", name: "Costco Wholesale Corp.", weight: 1.9 },
    { ticker: "NFLX", name: "Netflix Inc.", weight: 1.8 },
    { ticker: "ADBE", name: "Adobe Inc.", weight: 1.5 },
    { ticker: "AMD", name: "Advanced Micro Devices", weight: 1.4 },
    { ticker: "QCOM", name: "Qualcomm Inc.", weight: 1.3 },
    { ticker: "INTU", name: "Intuit Inc.", weight: 1.0 },
    { ticker: "CSCO", name: "Cisco Systems Inc.", weight: 0.92 },
    { ticker: "AMAT", name: "Applied Materials Inc.", weight: 0.88 },
    { ticker: "PEP", name: "PepsiCo Inc.", weight: 0.82 },
    { ticker: "TXN", name: "Texas Instruments Inc.", weight: 0.77 },
    { ticker: "HON", name: "Honeywell International", weight: 0.72 },
  ],
  // ── ADDITIONAL ETFs ──────────────────────────────────────────────
  ARKK: [
    { ticker: "TSLA", name: "Tesla Inc.", weight: 9.8 },
    { ticker: "ROKU", name: "Roku Inc.", weight: 7.5 },
    { ticker: "COIN", name: "Coinbase Global Inc.", weight: 6.8 },
    { ticker: "SQ", name: "Block Inc.", weight: 6.2 },
    { ticker: "CRSP", name: "CRISPR Therapeutics AG", weight: 5.4 },
    { ticker: "EXAS", name: "Exact Sciences Corp.", weight: 5.1 },
    { ticker: "SPOT", name: "Spotify Technology SA", weight: 4.9 },
    { ticker: "TDOC", name: "Teladoc Health Inc.", weight: 4.5 },
    { ticker: "PATH", name: "UiPath Inc.", weight: 4.2 },
    { ticker: "TWLO", name: "Twilio Inc.", weight: 3.8 },
    { ticker: "ZM", name: "Zoom Video Communications", weight: 3.5 },
    { ticker: "BEAM", name: "Beam Therapeutics Inc.", weight: 3.1 },
    { ticker: "PACB", name: "Pacific Biosciences of CA", weight: 2.8 },
    { ticker: "RXRX", name: "Recursion Pharmaceuticals", weight: 2.6 },
    { ticker: "NTLA", name: "Intellia Therapeutics Inc.", weight: 2.4 },
    { ticker: "TXG", name: "10x Genomics Inc.", weight: 2.2 },
    { ticker: "DNA", name: "Ginkgo Bioworks Holdings", weight: 2.0 },
    { ticker: "FATE", name: "Fate Therapeutics Inc.", weight: 1.8 },
    { ticker: "EDIT", name: "Editas Medicine Inc.", weight: 1.6 },
    { ticker: "VERV", name: "Verve Therapeutics Inc.", weight: 1.4 },
  ],
  ARKX: [
    { ticker: "KTOS", name: "Kratos Defense & Security", weight: 9.5 },
    { ticker: "RKLB", name: "Rocket Lab USA Inc.", weight: 9.2 },
    { ticker: "BKSY", name: "BlackSky Technology Inc.", weight: 8.8 },
    { ticker: "SPCE", name: "Virgin Galactic Holdings", weight: 7.5 },
    { ticker: "IRDM", name: "Iridium Communications Inc.", weight: 6.8 },
    { ticker: "AJRD", name: "Aerojet Rocketdyne Holdings", weight: 6.2 },
    { ticker: "TRMB", name: "Trimble Inc.", weight: 5.8 },
    { ticker: "PRNT", name: "3D Printing ETF", weight: 5.5 },
    { ticker: "IZRL", name: "ARK Israel Innovative Tech ETF", weight: 5.2 },
    { ticker: "GFAI", name: "Guardforce AI Co.", weight: 4.8 },
    { ticker: "QQQ", name: "Invesco QQQ Trust", weight: 4.5 },
    { ticker: "MKFG", name: "Markforged Holding Corp.", weight: 4.1 },
    { ticker: "OUST", name: "Ouster Inc.", weight: 3.8 },
    { ticker: "ASTR", name: "Astra Space Inc.", weight: 3.5 },
    { ticker: "MNTS", name: "Momentus Inc.", weight: 3.2 },
    { ticker: "VORB", name: "Virgin Orbit Holdings Inc.", weight: 2.8 },
    { ticker: "ATRO", name: "Astronics Corp.", weight: 2.5 },
    { ticker: "HEI", name: "HEICO Corp.", weight: 2.2 },
    { ticker: "TSAT", name: "Telesat Corp.", weight: 2.0 },
    { ticker: "MAXR", name: "Maxar Technologies Inc.", weight: 1.8 },
  ],
  ARKG: [
    { ticker: "RXRX", name: "Recursion Pharmaceuticals", weight: 8.5 },
    { ticker: "CRSP", name: "CRISPR Therapeutics AG", weight: 7.8 },
    { ticker: "EXAS", name: "Exact Sciences Corp.", weight: 7.2 },
    { ticker: "BEAM", name: "Beam Therapeutics Inc.", weight: 6.8 },
    { ticker: "PACB", name: "Pacific Biosciences of CA", weight: 6.5 },
    { ticker: "NTLA", name: "Intellia Therapeutics Inc.", weight: 6.1 },
    { ticker: "TDOC", name: "Teladoc Health Inc.", weight: 5.8 },
    { ticker: "FATE", name: "Fate Therapeutics Inc.", weight: 5.2 },
    { ticker: "EDIT", name: "Editas Medicine Inc.", weight: 4.8 },
    { ticker: "TXG", name: "10x Genomics Inc.", weight: 4.4 },
    { ticker: "VERV", name: "Verve Therapeutics Inc.", weight: 4.0 },
    { ticker: "DNLI", name: "Denali Therapeutics Inc.", weight: 3.6 },
    { ticker: "SGMO", name: "Sangamo Therapeutics Inc.", weight: 3.2 },
    { ticker: "NVTA", name: "Invitae Corp.", weight: 2.8 },
    { ticker: "GH", name: "Guardant Health Inc.", weight: 2.5 },
    { ticker: "MASS", name: "908 Devices Inc.", weight: 2.2 },
    { ticker: "IOVA", name: "Iovance Biotherapeutics Inc.", weight: 2.0 },
    { ticker: "VCNX", name: "Vaccinex Inc.", weight: 1.8 },
    { ticker: "OMER", name: "Omeros Corp.", weight: 1.5 },
    { ticker: "HOOK", name: "HOOKIPA Pharma Inc.", weight: 1.2 },
  ],
  XBI: [
    { ticker: "IONS", name: "Ionis Pharmaceuticals Inc.", weight: 2.8 },
    { ticker: "RARE", name: "Ultragenyx Pharmaceutical", weight: 2.7 },
    { ticker: "SRPT", name: "Sarepta Therapeutics Inc.", weight: 2.6 },
    { ticker: "INSM", name: "Insmed Inc.", weight: 2.5 },
    { ticker: "PCVX", name: "Vaxcyte Inc.", weight: 2.4 },
    { ticker: "MRNA", name: "Moderna Inc.", weight: 2.3 },
    { ticker: "VRTX", name: "Vertex Pharmaceuticals Inc.", weight: 2.2 },
    { ticker: "RCUS", name: "Arcus Biosciences Inc.", weight: 2.1 },
    { ticker: "ALKS", name: "Alkermes PLC", weight: 2.0 },
    { ticker: "ACAD", name: "ACADIA Pharmaceuticals Inc.", weight: 1.9 },
    { ticker: "KRYS", name: "Krystal Biotech Inc.", weight: 1.9 },
    { ticker: "CYTK", name: "Cytokinetics Inc.", weight: 1.8 },
    { ticker: "FOLD", name: "Amicus Therapeutics Inc.", weight: 1.8 },
    { ticker: "MDGL", name: "Madrigal Pharmaceuticals Inc.", weight: 1.7 },
    { ticker: "BLUE", name: "bluebird bio Inc.", weight: 1.7 },
    { ticker: "FATE", name: "Fate Therapeutics Inc.", weight: 1.6 },
    { ticker: "BEAM", name: "Beam Therapeutics Inc.", weight: 1.6 },
    { ticker: "CRSP", name: "CRISPR Therapeutics AG", weight: 1.5 },
    { ticker: "EDIT", name: "Editas Medicine Inc.", weight: 1.5 },
    { ticker: "EXAS", name: "Exact Sciences Corp.", weight: 1.4 },
  ],
  IBB: [
    { ticker: "AMGN", name: "Amgen Inc.", weight: 8.5 },
    { ticker: "GILD", name: "Gilead Sciences Inc.", weight: 7.2 },
    { ticker: "VRTX", name: "Vertex Pharmaceuticals Inc.", weight: 6.8 },
    { ticker: "REGN", name: "Regeneron Pharmaceuticals", weight: 6.5 },
    { ticker: "MRNA", name: "Moderna Inc.", weight: 5.8 },
    { ticker: "BIIB", name: "Biogen Inc.", weight: 5.2 },
    { ticker: "ILMN", name: "Illumina Inc.", weight: 4.8 },
    { ticker: "ALNY", name: "Alnylam Pharmaceuticals Inc.", weight: 4.5 },
    { ticker: "IONS", name: "Ionis Pharmaceuticals Inc.", weight: 4.1 },
    { ticker: "SGEN", name: "Seagen Inc.", weight: 3.8 },
    { ticker: "EXAS", name: "Exact Sciences Corp.", weight: 3.5 },
    { ticker: "SRPT", name: "Sarepta Therapeutics Inc.", weight: 3.2 },
    { ticker: "BMRN", name: "BioMarin Pharmaceutical Inc.", weight: 3.0 },
    { ticker: "INCY", name: "Incyte Corp.", weight: 2.8 },
    { ticker: "RARE", name: "Ultragenyx Pharmaceutical", weight: 2.6 },
    { ticker: "NBIX", name: "Neurocrine Biosciences Inc.", weight: 2.4 },
    { ticker: "ACAD", name: "ACADIA Pharmaceuticals Inc.", weight: 2.2 },
    { ticker: "FOLD", name: "Amicus Therapeutics Inc.", weight: 2.0 },
    { ticker: "RCUS", name: "Arcus Biosciences Inc.", weight: 1.8 },
    { ticker: "HALO", name: "Halozyme Therapeutics Inc.", weight: 1.6 },
  ],
  GLD: [
    { ticker: "GOLD_BULLION", name: "Physical Gold Bullion", weight: 99.5 },
    { ticker: "CASH", name: "Cash & Equivalents", weight: 0.5 },
  ],
  SLV: [
    { ticker: "SILVER_BULLION", name: "Physical Silver Bullion", weight: 99.5 },
    { ticker: "CASH", name: "Cash & Equivalents", weight: 0.5 },
  ],
  IAU: [
    { ticker: "GOLD_BULLION", name: "Physical Gold Bullion", weight: 99.5 },
    { ticker: "CASH", name: "Cash & Equivalents", weight: 0.5 },
  ],
  VYM: [
    { ticker: "JPM", name: "JPMorgan Chase & Co.", weight: 4.2 },
    { ticker: "ABBV", name: "AbbVie Inc.", weight: 3.8 },
    { ticker: "XOM", name: "Exxon Mobil Corp.", weight: 3.5 },
    { ticker: "JNJ", name: "Johnson & Johnson", weight: 3.2 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 3.0 },
    { ticker: "HD", name: "Home Depot Inc.", weight: 2.8 },
    { ticker: "PG", name: "Procter & Gamble Co.", weight: 2.6 },
    { ticker: "MRK", name: "Merck & Co Inc.", weight: 2.4 },
    { ticker: "CVX", name: "Chevron Corp.", weight: 2.2 },
    { ticker: "KO", name: "Coca-Cola Co.", weight: 2.0 },
    { ticker: "CSCO", name: "Cisco Systems Inc.", weight: 1.9 },
    { ticker: "PEP", name: "PepsiCo Inc.", weight: 1.8 },
    { ticker: "VZ", name: "Verizon Communications", weight: 1.7 },
    { ticker: "WFC", name: "Wells Fargo & Co.", weight: 1.6 },
    { ticker: "MS", name: "Morgan Stanley", weight: 1.5 },
    { ticker: "TXN", name: "Texas Instruments Inc.", weight: 1.4 },
    { ticker: "PFE", name: "Pfizer Inc.", weight: 1.3 },
    { ticker: "BMY", name: "Bristol-Myers Squibb Co.", weight: 1.2 },
    { ticker: "T", name: "AT&T Inc.", weight: 1.1 },
    { ticker: "USB", name: "U.S. Bancorp", weight: 1.0 },
  ],
  SMH: [
    { ticker: "NVDA", name: "NVIDIA Corp.", weight: 20.2 },
    { ticker: "TSM", name: "Taiwan Semiconductor ADR", weight: 13.8 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 8.5 },
    { ticker: "ASML", name: "ASML Holding NV ADR", weight: 7.2 },
    { ticker: "AMD", name: "Advanced Micro Devices", weight: 6.8 },
    { ticker: "QCOM", name: "Qualcomm Inc.", weight: 5.4 },
    { ticker: "INTC", name: "Intel Corp.", weight: 4.9 },
    { ticker: "AMAT", name: "Applied Materials Inc.", weight: 4.5 },
    { ticker: "TXN", name: "Texas Instruments Inc.", weight: 4.1 },
    { ticker: "LRCX", name: "Lam Research Corp.", weight: 3.8 },
    { ticker: "KLAC", name: "KLA Corp.", weight: 3.5 },
    { ticker: "MU", name: "Micron Technology Inc.", weight: 3.2 },
    { ticker: "MRVL", name: "Marvell Technology Inc.", weight: 3.0 },
    { ticker: "ON", name: "ON Semiconductor Corp.", weight: 2.8 },
    { ticker: "MPWR", name: "Monolithic Power Systems Inc.", weight: 2.5 },
    { ticker: "SWKS", name: "Skyworks Solutions Inc.", weight: 2.2 },
    { ticker: "NXPI", name: "NXP Semiconductors NV", weight: 2.0 },
    { ticker: "STM", name: "STMicroelectronics NV", weight: 1.8 },
    { ticker: "OLED", name: "Universal Display Corp.", weight: 1.5 },
    { ticker: "WOLF", name: "Wolfspeed Inc.", weight: 1.2 },
  ],
  SOXX: [
    { ticker: "NVDA", name: "NVIDIA Corp.", weight: 9.8 },
    { ticker: "AVGO", name: "Broadcom Inc.", weight: 9.5 },
    { ticker: "AMD", name: "Advanced Micro Devices", weight: 8.2 },
    { ticker: "QCOM", name: "Qualcomm Inc.", weight: 7.8 },
    { ticker: "INTC", name: "Intel Corp.", weight: 7.2 },
    { ticker: "AMAT", name: "Applied Materials Inc.", weight: 6.8 },
    { ticker: "TXN", name: "Texas Instruments Inc.", weight: 6.5 },
    { ticker: "LRCX", name: "Lam Research Corp.", weight: 6.0 },
    { ticker: "KLAC", name: "KLA Corp.", weight: 5.5 },
    { ticker: "MU", name: "Micron Technology Inc.", weight: 5.0 },
    { ticker: "ON", name: "ON Semiconductor Corp.", weight: 4.5 },
    { ticker: "MCHP", name: "Microchip Technology Inc.", weight: 4.0 },
    { ticker: "SWKS", name: "Skyworks Solutions Inc.", weight: 3.5 },
    { ticker: "NXPI", name: "NXP Semiconductors NV", weight: 3.2 },
    { ticker: "MPWR", name: "Monolithic Power Systems Inc.", weight: 2.8 },
    { ticker: "MRVL", name: "Marvell Technology Inc.", weight: 2.5 },
    { ticker: "TSM", name: "Taiwan Semiconductor ADR", weight: 2.2 },
    { ticker: "STM", name: "STMicroelectronics NV", weight: 2.0 },
    { ticker: "OLED", name: "Universal Display Corp.", weight: 1.8 },
    { ticker: "ADI", name: "Analog Devices Inc.", weight: 1.5 },
  ],
  XLE: [
    { ticker: "XOM", name: "Exxon Mobil Corp.", weight: 22.5 },
    { ticker: "CVX", name: "Chevron Corp.", weight: 18.2 },
    { ticker: "COP", name: "ConocoPhillips", weight: 8.5 },
    { ticker: "SLB", name: "Schlumberger Ltd.", weight: 5.2 },
    { ticker: "MPC", name: "Marathon Petroleum Corp.", weight: 4.8 },
    { ticker: "EOG", name: "EOG Resources Inc.", weight: 4.5 },
    { ticker: "PSX", name: "Phillips 66", weight: 4.2 },
    { ticker: "VLO", name: "Valero Energy Corp.", weight: 4.0 },
    { ticker: "PXD", name: "Pioneer Natural Resources", weight: 3.8 },
    { ticker: "OXY", name: "Occidental Petroleum Corp.", weight: 3.5 },
    { ticker: "HAL", name: "Halliburton Co.", weight: 3.2 },
    { ticker: "DVN", name: "Devon Energy Corp.", weight: 3.0 },
    { ticker: "HES", name: "Hess Corp.", weight: 2.8 },
    { ticker: "BKR", name: "Baker Hughes Co.", weight: 2.5 },
    { ticker: "FANG", name: "Diamondback Energy Inc.", weight: 2.2 },
    { ticker: "MRO", name: "Marathon Oil Corp.", weight: 2.0 },
    { ticker: "APA", name: "APA Corp.", weight: 1.8 },
    { ticker: "OVV", name: "Ovintiv Inc.", weight: 1.5 },
    { ticker: "TRGP", name: "Targa Resources Corp.", weight: 1.2 },
    { ticker: "WMB", name: "Williams Companies Inc.", weight: 1.0 },
  ],
  XLF: [
    { ticker: "BRK.B", name: "Berkshire Hathaway B", weight: 13.5 },
    { ticker: "JPM", name: "JPMorgan Chase & Co.", weight: 11.8 },
    { ticker: "BAC", name: "Bank of America Corp.", weight: 7.2 },
    { ticker: "WFC", name: "Wells Fargo & Co.", weight: 5.8 },
    { ticker: "GS", name: "Goldman Sachs Group Inc.", weight: 5.2 },
    { ticker: "MS", name: "Morgan Stanley", weight: 4.8 },
    { ticker: "SPGI", name: "S&P Global Inc.", weight: 4.5 },
    { ticker: "BLK", name: "BlackRock Inc.", weight: 4.2 },
    { ticker: "C", name: "Citigroup Inc.", weight: 3.8 },
    { ticker: "AXP", name: "American Express Co.", weight: 3.5 },
    { ticker: "CB", name: "Chubb Ltd.", weight: 3.2 },
    { ticker: "USB", name: "U.S. Bancorp", weight: 2.8 },
    { ticker: "PNC", name: "PNC Financial Services", weight: 2.5 },
    { ticker: "CME", name: "CME Group Inc.", weight: 2.2 },
    { ticker: "TFC", name: "Truist Financial Corp.", weight: 2.0 },
    { ticker: "ICE", name: "Intercontinental Exchange Inc.", weight: 1.8 },
    { ticker: "MET", name: "MetLife Inc.", weight: 1.6 },
    { ticker: "AIG", name: "American International Group", weight: 1.4 },
    { ticker: "COF", name: "Capital One Financial Corp.", weight: 1.2 },
    { ticker: "AFL", name: "Aflac Inc.", weight: 1.0 },
  ],
  // AIS — iShares MSCI Israel ETF (example ticker, confirm)
  EIS: [
    { ticker: "CHECK_POINT", name: "Check Point Software Tech", weight: 12.5 },
    { ticker: "NICE", name: "NICE Systems Ltd.", weight: 9.8 },
    { ticker: "CYBR", name: "CyberArk Software Ltd.", weight: 8.2 },
    { ticker: "TEVA", name: "Teva Pharmaceutical Industries", weight: 7.5 },
    { ticker: "CHKP", name: "Check Point Software", weight: 7.0 },
    { ticker: "MNDY", name: "monday.com Ltd.", weight: 6.5 },
    { ticker: "WIX", name: "Wix.com Ltd.", weight: 5.8 },
    { ticker: "FIVERR", name: "Fiverr International Ltd.", weight: 5.2 },
    { ticker: "GLBE", name: "Global-E Online Ltd.", weight: 4.8 },
    { ticker: "DDOG", name: "Datadog Inc.", weight: 4.5 },
    { ticker: "CELH", name: "Celsius Holdings Inc.", weight: 4.0 },
    { ticker: "INMD", name: "InMode Ltd.", weight: 3.6 },
    { ticker: "GMAB", name: "Genmab A/S ADR", weight: 3.2 },
    { ticker: "RADCOM", name: "RADCOM Ltd.", weight: 2.8 },
    { ticker: "NNDM", name: "Nano Dimension Ltd.", weight: 2.5 },
    { ticker: "SIEVERT", name: "Sievert Storey Corp.", weight: 2.2 },
    { ticker: "LPSN", name: "LivePerson Inc.", weight: 2.0 },
    { ticker: "PERI", name: "Perion Network Ltd.", weight: 1.8 },
    { ticker: "EMKR", name: "EMCORE Corp.", weight: 1.5 },
    { ticker: "CEVA", name: "CEVA Inc.", weight: 1.2 },
  ],
  KWEB: [
    { ticker: "BABA", name: "Alibaba Group Holding ADR", weight: 10.5 },
    { ticker: "TENCENT", name: "Tencent Holdings ADR", weight: 9.8 },
    { ticker: "JD", name: "JD.com Inc. ADR", weight: 8.2 },
    { ticker: "BIDU", name: "Baidu Inc. ADR", weight: 7.5 },
    { ticker: "PDD", name: "PDD Holdings Inc. ADR", weight: 7.0 },
    { ticker: "MEITUAN", name: "Meituan ADR", weight: 6.5 },
    { ticker: "NIO", name: "NIO Inc. ADR", weight: 6.0 },
    { ticker: "XPEV", name: "XPeng Inc. ADR", weight: 5.5 },
    { ticker: "LI", name: "Li Auto Inc. ADR", weight: 5.0 },
    { ticker: "EDU", name: "New Oriental Education ADR", weight: 4.5 },
    { ticker: "NTES", name: "NetEase Inc. ADR", weight: 4.2 },
    { ticker: "VNET", name: "VNET Group Inc. ADR", weight: 3.8 },
    { ticker: "BILI", name: "Bilibili Inc. ADR", weight: 3.5 },
    { ticker: "IQ", name: "iQIYI Inc. ADR", weight: 3.2 },
    { ticker: "ATHM", name: "Autohome Inc. ADR", weight: 2.8 },
    { ticker: "JOBS", name: "51job Inc. ADR", weight: 2.5 },
    { ticker: "FINV", name: "FinVolution Group ADR", weight: 2.2 },
    { ticker: "WB", name: "Weibo Corp. ADR", weight: 2.0 },
    { ticker: "MOMO", name: "Hello Group Inc. ADR", weight: 1.8 },
    { ticker: "LOGI", name: "Logitech International SA", weight: 1.5 },
  ],
  DIA: [
    { ticker: "UNH", name: "UnitedHealth Group Inc.", weight: 9.8 },
    { ticker: "GS", name: "Goldman Sachs Group Inc.", weight: 7.5 },
    { ticker: "MSFT", name: "Microsoft Corp.", weight: 6.8 },
    { ticker: "HD", name: "Home Depot Inc.", weight: 6.5 },
    { ticker: "MCD", name: "McDonald's Corp.", weight: 5.8 },
    { ticker: "CAT", name: "Caterpillar Inc.", weight: 5.5 },
    { ticker: "AMGN", name: "Amgen Inc.", weight: 5.2 },
    { ticker: "BA", name: "Boeing Co.", weight: 4.8 },
    { ticker: "V", name: "Visa Inc.", weight: 4.5 },
    { ticker: "HON", name: "Honeywell International", weight: 4.2 },
    { ticker: "IBM", name: "International Business Machines", weight: 3.8 },
    { ticker: "AAPL", name: "Apple Inc.", weight: 3.5 },
    { ticker: "TRV", name: "Travelers Companies Inc.", weight: 3.2 },
    { ticker: "JPM", name: "JPMorgan Chase & Co.", weight: 3.0 },
    { ticker: "JNJ", name: "Johnson & Johnson", weight: 2.8 },
    { ticker: "SHW", name: "Sherwin-Williams Co.", weight: 2.5 },
    { ticker: "AXP", name: "American Express Co.", weight: 2.2 },
    { ticker: "CRM", name: "Salesforce Inc.", weight: 2.0 },
    { ticker: "NKE", name: "Nike Inc.", weight: 1.8 },
    { ticker: "MMM", name: "3M Co.", weight: 1.5 },
  ],
  JEPI: [
    { ticker: "ABBV", name: "AbbVie Inc.", weight: 2.2 },
    { ticker: "ACGL", name: "Arch Capital Group", weight: 2.0 },
    { ticker: "TMUS", name: "T-Mobile US Inc.", weight: 1.9 },
    { ticker: "AMGN", name: "Amgen Inc.", weight: 1.8 },
    { ticker: "BSX", name: "Boston Scientific Corp.", weight: 1.8 },
    { ticker: "MSFT", name: "Microsoft Corp.", weight: 1.7 },
    { ticker: "CME", name: "CME Group Inc.", weight: 1.7 },
    { ticker: "SO", name: "Southern Company", weight: 1.6 },
    { ticker: "MCD", name: "McDonald's Corp.", weight: 1.6 },
    { ticker: "AMP", name: "Ameriprise Financial", weight: 1.5 },
    { ticker: "TJX", name: "TJX Companies Inc.", weight: 1.5 },
    { ticker: "PGR", name: "Progressive Corp.", weight: 1.4 },
    { ticker: "MRK", name: "Merck & Co Inc.", weight: 1.4 },
    { ticker: "AAPL", name: "Apple Inc.", weight: 1.3 },
    { ticker: "UNH", name: "UnitedHealth Group Inc.", weight: 1.3 },
    { ticker: "WMT", name: "Walmart Inc.", weight: 1.2 },
    { ticker: "KO", name: "Coca-Cola Co.", weight: 1.2 },
    { ticker: "JPM", name: "JPMorgan Chase & Co.", weight: 1.1 },
    { ticker: "HD", name: "Home Depot Inc.", weight: 1.1 },
    { ticker: "PG", name: "Procter & Gamble Co.", weight: 1.0 },
  ],
  AIS: [
    { ticker: "000660", name: "SK hynix Inc.", weight: 8.94 },
    { ticker: "MU", name: "Micron Technology Inc.", weight: 6.86 },
    { ticker: "VRT", name: "Vertiv Holdings Co.", weight: 5.44 },
    { ticker: "TSM", name: "Taiwan Semiconductor Mfg. Co.", weight: 4.43 },
    { ticker: "INTC", name: "Intel Corp.", weight: 4.05 },
    { ticker: "GEV", name: "GE Vernova Inc.", weight: 3.92 },
    { ticker: "NVDA", name: "NVIDIA Corp.", weight: 3.69 },
    { ticker: "VICR", name: "Vicor Corp.", weight: 3.58 },
    { ticker: "601138", name: "Foxconn Industrial Internet Co.", weight: 3.33 },
    { ticker: "AMD", name: "Advanced Micro Devices Inc.", weight: 3.03 },
    { ticker: "MRVL", name: "Marvell Technology Inc.", weight: 3.12 },
    { ticker: "CVLT", name: "Commvault Systems Inc.", weight: 3.09 },
    { ticker: "NTNX", name: "Nutanix Inc.", weight: 3.03 },
    { ticker: "SIMO", name: "Silicon Motion Technology Corp.", weight: 2.93 },
    { ticker: "ALAB", name: "Astera Labs Inc.", weight: 2.61 },
    { ticker: "EXTR", name: "Extreme Networks Inc.", weight: 2.49 },
    { ticker: "ANET", name: "Arista Networks Inc.", weight: 2.40 },
    { ticker: "GLW", name: "Corning Inc.", weight: 2.35 },
    { ticker: "GFS", name: "GlobalFoundries Inc.", weight: 2.29 },
    { ticker: "ARM", name: "Arm Holdings plc", weight: 1.93 },
  ],
};

/**
 * Fetches ETF holdings from stockanalysis.com for ANY US ETF ticker.
 * Returns up to 25 top holdings with weights.
 */
async function fetchFromStockAnalysis(ticker: string): Promise<HoldingRow[] | null> {
  try {
    const url = `https://stockanalysis.com/etf/${ticker.toLowerCase()}/holdings/__data.json`;
    const resp = await axios.get(url, {
      headers: {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "Accept": "application/json",
        "Referer": `https://stockanalysis.com/etf/${ticker.toLowerCase()}/holdings/`,
      },
      timeout: 10000,
    });

    const nodes = resp.data?.nodes;
    if (!Array.isArray(nodes)) return null;

    // Find the data node that contains holdings (has objects with {no, n, s} keys)
    let holdingsData: unknown[] | null = null;
    for (const node of nodes) {
      const data = node?.data;
      if (!Array.isArray(data)) continue;
      const hasHoldingPattern = data.some(
        (item: unknown) => item !== null && typeof item === "object" &&
          "no" in (item as object) && "n" in (item as object) && "s" in (item as object)
      );
      if (hasHoldingPattern) {
        holdingsData = data;
        break;
      }
    }

    if (!holdingsData) return null;

    // Parse the flat array: each holding is represented as an index map {no, n, s, as, sh}
    const holdings: HoldingRow[] = [];
    for (let i = 0; i < holdingsData.length; i++) {
      const item = holdingsData[i];
      if (!item || typeof item !== "object") continue;
      const obj = item as Record<string, unknown>;
      if (!("no" in obj) || !("n" in obj) || !("s" in obj)) continue;

      const resolve = (idx: unknown): unknown =>
        typeof idx === "number" && idx < holdingsData!.length
          ? holdingsData![idx]
          : idx;

      const symbolRaw = resolve(obj.s);
      const nameRaw = resolve(obj.n);
      const weightRaw = "as" in obj ? resolve(obj.as) : null;

      if (typeof symbolRaw !== "string" || typeof nameRaw !== "string") continue;

      const symbol = symbolRaw.startsWith("$") ? symbolRaw.slice(1) : symbolRaw;
      const name = nameRaw;
      let weight = 0;
      if (typeof weightRaw === "string" && weightRaw.includes("%")) {
        weight = parseFloat(weightRaw.replace("%", "").trim()) || 0;
      } else if (typeof weightRaw === "number") {
        weight = weightRaw;
      }

      if (symbol && name && symbol.length <= 10) {
        holdings.push({ ticker: symbol, name, weight });
      }
    }

    if (holdings.length >= 3) return holdings.slice(0, 25);
    return null;
  } catch {
    return null;
  }
}

export async function fetchEtfHoldings(ticker: string): Promise<HoldingRow[]> {
  const upper = ticker.toUpperCase();

  // 1. Always try live fetch first — works for ANY US ETF
  const live = await fetchFromStockAnalysis(upper);
  if (live && live.length >= 3) return live;

  // 2. Curated fallback (offline/cached data for common ETFs)
  if (FALLBACK_HOLDINGS[upper]) {
    return FALLBACK_HOLDINGS[upper];
  }

  // 3. Nothing worked
  throw new Error(
    `Could not fetch holdings for ${upper}. Please verify the ticker is a valid US ETF and try again.`
  );
}
